### ISSUE TITLE
Fix websurfer agent issue

### ISSUE THREAD

**Issue by kumaranvpl** [airtai/fastagency#394]

**Comment by kumaranvpl** [comment]
```txt
2024-06-21 08:25:52,686 ERROR    - FastAgency | initiate_workers | chat.server.initiate_chat | 9e872af6-a - Error in chat: Error code: 400 - {'error': {'message': "An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'. The following tool_call_ids did not have response messages: call_CIcCVzHbQ5TTDqqTK2QWm5kl", 'type': 'invalid_request_error', 'param': 'messages.[5].role', 'code': None}}
2024-06-21 08:25:52,687 ERROR    - FastAgency | initiate_workers | chat.server.initiate_chat | 9e872af6-a - Traceback (most recent call last):
  File "/workspaces/fastagency/./fastagency/io/ionats.py", line 198, in start_chat
    chat_result = initiate_chat(body.msg)
  File "/workspaces/fastagency/./fastagency/models/teams/multi_agent_team.py", line 35, in initiate_chat
    return self.agents[0].initiate_chat(  # type: ignore[no-any-return]
  File "/home/vscode/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 1018, in initiate_chat
    self.send(msg2send, recipient, silent=silent)
  File "/home/vscode/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 655, in send
    recipient.receive(message, self, request_reply, silent)
  File "/home/vscode/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 818, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "/home/vscode/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 1972, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/home/vscode/.local/lib/python3.10/site-packages/autogen/agentchat/groupchat.py", line 1052, in run_chat
    reply = speaker.generate_reply(sender=self)
  File "/home/vscode/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 1972, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/home/vscode/.local/lib/python3.10/site-packages/autogen/agentchat/contrib/web_surfer.py", line 286, in generate_surfer_reply
    self._user_proxy.send(messages[-1]["content"], self._assistant, request_reply=True, silent=True)
  File "/home/vscode/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 655, in send
    recipient.receive(message, self, request_reply, silent)
  File "/home/vscode/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 818, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "/home/vscode/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 1972, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/home/vscode/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 1340, in generate_oai_reply
    extracted_response = self._generate_oai_reply_from_client(
  File "/home/vscode/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 1359, in _generate_oai_reply_from_client
    response = llm_client.create(
  File "/home/vscode/.local/lib/python3.10/site-packages/autogen/oai/client.py", line 662, in create
    response = client.create(params)
  File "/home/vscode/.local/lib/python3.10/site-packages/autogen/oai/client.py", line 285, in create
    response = completions.create(**params)
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 606, in create
    return self._post(
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
  File "/home/vscode/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'. The following tool_call_ids did not have response messages: call_CIcCVzHbQ5TTDqqTK2QWm5kl", 'type': 'invalid_request_error', 'param': 'messages.[5].role', 'code': None}}
```
